# Generated by Django 5.2.1 on 2025-05-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='ci',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
