# Generated by Django 5.2 on 2025-06-13 05:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Foto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "imag",
                    models.ImageField(blank=True, null=True, upload_to="galeria/"),
                ),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Paquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=7)),
                ("descripcion", models.TextField()),
                (
                    "imag",
                    models.ImageField(blank=True, null=True, upload_to="paquete/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=150)),
                ("ci", models.IntegerField(primary_key=True, serialize=False)),
                ("salario", models.IntegerField()),
                ("puesto", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=150)),
                ("usuario", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254)),
                ("telefono", models.IntegerField()),
                ("password", models.TextField()),
                (
                    "rol",
                    models.CharField(
                        choices=[("cliente", "Cliente"), ("admin", "Admin")],
                        default="cliente",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promocion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("porcientoDesc", models.IntegerField()),
                (
                    "imag",
                    models.ImageField(blank=True, null=True, upload_to="[promocion]/"),
                ),
                (
                    "paquete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.paquete"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reseña",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clasificacion",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario", models.TextField()),
                (
                    "usuarioid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField(default="")),
                ("fecha", models.DateTimeField()),
                (
                    "paqueteid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.paquete"
                    ),
                ),
                (
                    "usuarioid",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usuario",
                    ),
                ),
            ],
        ),
    ]
