# Generated by Django 5.1.3 on 2025-03-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Admin'), ('moderador', 'Moderador')], default='cliente', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
