# Generated by Django 5.1.6 on 2025-03-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cliente_user_remove_customuser_rol_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
