# Generated by Django 5.1.3 on 2025-03-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='comentario',
            field=models.TextField(default='a'),
        ),
    ]
