# Generated by Django 5.1.3 on 2025-03-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_trabajador_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='rol',
            field=models.CharField(default='cliente', max_length=20),
        ),
    ]
