# Generated by Django 5.1.3 on 2025-02-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='clasificacion',
            field=models.IntegerField(choices=[(1, '1 - Muy Malo'), (2, '2 - Malo'), (3, '3 - Regular'), (4, '4 - Bueno'), (5, '5 - Excelente')], default=3),
        ),
    ]
