# Generated by Django 5.2.1 on 2025-05-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_producto_promocion_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='nombre',
        ),
    ]
