# Generated by Django 5.1.3 on 2025-03-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_puesto_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puesto',
            name='rol',
            field=models.CharField(max_length=20),
        ),
    ]
