# Generated by Django 5.1.3 on 2025-02-27 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reseña_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='clasificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
