# Generated by Django 5.1.3 on 2025-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cita_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='comentario',
            field=models.TextField(default=''),
        ),
    ]
