# Generated by Django 5.2 on 2025-06-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_producto_producto_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="foto",
            name="descripcion",
            field=models.TextField(default="Esto es una descripcion"),
            preserve_default=False,
        ),
    ]
