# Generated by Django 5.2 on 2025-06-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_foto_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocion",
            name="imag",
            field=models.ImageField(blank=True, null=True, upload_to="[promocion]/"),
        ),
    ]
