# Generated by Django 5.2.1 on 2025-05-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='calidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imag',
        ),
    ]
