# Generated by Django 5.2.1 on 2025-05-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
    ]
