# Generated by Django 5.2.1 on 2025-05-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
    ]
