# Generated by Django 5.2.1 on 2025-05-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_options'),
        ('servicios', '0002_servicio_duration'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='usuarioid',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='servicioid',
        ),
        migrations.AddField(
            model_name='cita',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='end',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='start',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('service', 'start'), name='unique_service_start'),
        ),
    ]
