# Generated by Django 5.2.1 on 2025-05-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_options_rename_usuarioid_cita_customer_and_more'),
        ('servicios', '0002_servicio_duration'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-start']},
        ),
        migrations.RemoveConstraint(
            model_name='cita',
            name='unique_service_start',
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('service', 'start')},
        ),
        migrations.AddField(
            model_name='cita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Marca de tiempo cuando se creó la cita', null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='customer',
            field=models.ForeignKey(help_text='Usuario que reservó la cita', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='end',
            field=models.DateTimeField(editable=False, help_text='Fecha y hora de fin calculada automáticamente', null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='service',
            field=models.ForeignKey(help_text='Servicio reservado', on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='start',
            field=models.DateTimeField(help_text='Fecha y hora de inicio de la cita', null=True),
        ),
        migrations.RemoveField(
            model_name='cita',
            name='create_at',
        ),
    ]
