# Generated by Django 5.2.1 on 2025-05-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='duration',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='imag',
            new_name='imagen',
        ),
    ]
